baseurl = "https://blascerecer.netlify.com"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Blas Cerecer"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Dimming one screen at a time"
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 31, 2019"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Blas Cerecer"
  website = "blascerecer.com"
  email = "blcerecer@gmail.com"
##  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "bcerecer"
##  gitlab = "username"
##  bitbucket = "username"
##  twitter = "username"
##  reddit = "username"
  linkedin = "blcerecer"
##  xing = "username"
##  stackoverflow = "users/XXXXXXX/username"
##  snapchat = "username"
##  instagram = "leblastoff"
##  youtube = "user/username" # or channel/channelname
##  soundcloud = "username"
##  spotify = "username"
##  bandcamp = "username"
##  itchio = "username"
##  vk = "username"
##  paypal = "username"
##  telegram = "username"
##  500px = "username"

